### ISSUE TITLE
Numbering Convention

### ISSUE THREAD

**Issue by Oblique82** [gapmiss/berean-study-bible-for-obsidian#1]
Thanks for this

I just wonder if the Chapter files should have leading zero's for numbers 1-9

Eg Genesis 01 instead of Genesis 1

This will allow the chapters to display in the correct order

**Comment by gapmiss** [comment]
Thank you for the feedback. Yes, I have contemplated this also. However, in Obsidian's file explorer, the chapters are sorted 1, 2, 3, etc. I have them sorted "**File name (A to Z)**." In addition, Psalms would have to be numbered 001, 002, 003, etc. because there are 150 chapters.

![CleanShot – Obsidian - berean-study-bible-for-obsidian - Obsidian v0 15 6 – 2022-07-23 at 11 34 50](https://user-images.githubusercontent.com/98914514/180611855-87818f32-315d-464e-a531-6517558fe093.png)

Having said all this, I could possibly regenerate the Markdown and add the zero padding to the chapter numbers. Let me know if this would help you.

**Comment by Oblique82** [comment]
Yes this make sense - thankyou for the clear explanation
